"""
Add ThaiBMA Market Data tables

Revision ID: add_thaibma_market_data
Revises: b5f5bc6bcf78
Create Date: 2026-02-05

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_thaibma_market_data'
down_revision = 'b5f5bc6bcf78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create thaibma_market_data table
    op.create_table(
        'thaibma_market_data',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('data_date', sa.Date(), nullable=False),
        sa.Column('security_id', sa.String(length=40), nullable=False),
        sa.Column('thaibma_symbol', sa.String(length=20), nullable=False),
        sa.Column('isin', sa.String(length=12), nullable=True),
        sa.Column('coupon_rate', sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column('maturity_date', sa.Date(), nullable=True),
        sa.Column('time_to_maturity_years', sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column('bond_type', sa.String(length=50), nullable=True),
        sa.Column('coupon_type', sa.String(length=20), nullable=True),
        sa.Column('rating_tris', sa.String(length=10), nullable=True),
        sa.Column('rating_fitch', sa.String(length=10), nullable=True),
        sa.Column('last_trade_date', sa.Date(), nullable=True),
        sa.Column('last_executed_yield', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('quoted_date', sa.Date(), nullable=True),
        sa.Column('quoted_yield', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('max_yield', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('min_yield', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('model_yield', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('static_spread_bp', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('market_yield', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('duration_metric', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('clean_price', sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column('accrued_interest', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('dirty_price', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('modified_duration', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('convexity', sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column('par_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('registration_status', sa.String(length=20), nullable=True),
        sa.Column('index_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('import_batch_id', sa.String(length=50), nullable=True),
        sa.Column('import_file_name', sa.String(length=100), nullable=False),
        sa.Column('import_timestamp', sa.DateTime(), nullable=True),
        sa.Column('is_valid', sa.Boolean(), nullable=True),
        sa.Column('validation_errors', sa.String(length=500), nullable=True),
        sa.Column('created_by', sa.String(length=40), nullable=True),
        sa.Column('updated_by', sa.String(length=40), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['security_id'], ['security_master.security_id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('security_id', 'data_date', name='uq_thaibma_security_date')
    )
    
    # Create indexes
    op.create_index('ix_thaibma_data_date', 'thaibma_market_data', ['data_date'])
    op.create_index('ix_thaibma_symbol_date', 'thaibma_market_data', ['thaibma_symbol', 'data_date'])
    op.create_index('ix_thaibma_price_lookup', 'thaibma_market_data', ['security_id', 'data_date', 'clean_price'])
    
    # Create market_data_import_log table
    op.create_table(
        'market_data_import_log',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('batch_id', sa.String(length=50), nullable=False),
        sa.Column('import_date', sa.Date(), nullable=False),
        sa.Column('file_name', sa.String(length=100), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=True),
        sa.Column('total_records', sa.Integer(), nullable=True),
        sa.Column('successful_records', sa.Integer(), nullable=True),
        sa.Column('failed_records', sa.Integer(), nullable=True),
        sa.Column('skipped_records', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.String(length=1000), nullable=True),
        sa.Column('error_details', sa.String(length=2000), nullable=True),
        sa.Column('price_movement_alerts', sa.Integer(), nullable=True),
        sa.Column('missing_securities', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.String(length=40), nullable=True),
        sa.Column('updated_by', sa.String(length=40), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('batch_id', name='uq_import_log_batch_id')
    )
    
    # Create indexes for import log
    op.create_index('ix_import_log_date', 'market_data_import_log', ['import_date'])
    op.create_index('ix_import_log_status', 'market_data_import_log', ['status'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_import_log_status', table_name='market_data_import_log')
    op.drop_index('ix_import_log_date', table_name='market_data_import_log')
    op.drop_table('market_data_import_log')
    op.drop_index('ix_thaibma_price_lookup', table_name='thaibma_market_data')
    op.drop_index('ix_thaibma_symbol_date', table_name='thaibma_market_data')
    op.drop_index('ix_thaibma_data_date', table_name='thaibma_market_data')
    op.drop_table('thaibma_market_data')
    # ### end Alembic commands ###
