"""initial_schema

Revision ID: b5f5bc6bcf78
Revises: 
Create Date: 2026-02-02 18:57:53.880790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f5bc6bcf78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('entity_master',
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_name_th', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('parent_entity_id', sa.String(length=40), nullable=True),
    sa.Column('bot_code', sa.String(length=13), nullable=True),
    sa.Column('swift_bic', sa.String(length=11), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['entity_master.entity_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('ix_entity_bot_code', 'entity_master', ['bot_code'], unique=False)
    op.create_index('ix_entity_swift', 'entity_master', ['swift_bic'], unique=False)
    op.create_table('haircut_matrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_type', sa.String(length=20), nullable=False),
    sa.Column('credit_rating', sa.String(length=10), nullable=True),
    sa.Column('tenor_from_days', sa.Integer(), nullable=False),
    sa.Column('tenor_to_days', sa.Integer(), nullable=False),
    sa.Column('haircut_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_type', 'credit_rating', 'tenor_from_days', 'effective_date', name='uq_haircut_definition')
    )
    op.create_index('ix_haircut_security_type', 'haircut_matrix', ['security_type', 'credit_rating'], unique=False)
    op.create_table('cash_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_date', sa.Date(), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=40), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('inflows', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('outflows', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('projected_t1_inflow', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('projected_t1_outflow', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('projected_t2_inflow', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('projected_t2_outflow', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_date', 'entity_id', 'currency', 'account_type', name='uq_cash_position')
    )
    op.create_index('ix_cash_pos_date', 'cash_positions', ['position_date'], unique=False)
    op.create_index('ix_cash_pos_entity', 'cash_positions', ['entity_id'], unique=False)
    op.create_table('counterparty_master',
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=False),
    sa.Column('counterparty_name_th', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('counterparty_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('bot_code', sa.String(length=13), nullable=True),
    sa.Column('swift_bic', sa.String(length=11), nullable=True),
    sa.Column('tsd_participant_code', sa.String(length=20), nullable=True),
    sa.Column('bahtnet_member_code', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('has_isda', sa.Boolean(), nullable=False),
    sa.Column('has_gmra', sa.Boolean(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.PrimaryKeyConstraint('counterparty_id')
    )
    op.create_index('ix_counterparty_bot_code', 'counterparty_master', ['bot_code'], unique=False)
    op.create_index('ix_counterparty_type', 'counterparty_master', ['counterparty_type'], unique=False)
    op.create_table('portfolio_master',
    sa.Column('portfolio_id', sa.String(length=40), nullable=False),
    sa.Column('portfolio_code', sa.String(length=20), nullable=False),
    sa.Column('portfolio_name', sa.String(length=255), nullable=False),
    sa.Column('portfolio_name_th', sa.String(length=255), nullable=True),
    sa.Column('portfolio_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('tfrs9_classification', sa.String(length=20), nullable=False),
    sa.Column('business_model', sa.String(length=50), nullable=False),
    sa.Column('gl_account', sa.String(length=20), nullable=True),
    sa.Column('cost_center', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id'),
    sa.UniqueConstraint('portfolio_code')
    )
    op.create_table('security_master',
    sa.Column('security_id', sa.String(length=40), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('security_name', sa.String(length=255), nullable=False),
    sa.Column('security_name_th', sa.String(length=255), nullable=True),
    sa.Column('security_type', sa.String(length=20), nullable=False),
    sa.Column('issuer_type', sa.String(length=20), nullable=False),
    sa.Column('issuer_id', sa.String(length=40), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('coupon_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('coupon_frequency', sa.Integer(), nullable=False),
    sa.Column('day_count_convention', sa.String(length=20), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('minimum_denomination', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('credit_rating', sa.String(length=10), nullable=True),
    sa.Column('rating_agency', sa.String(length=50), nullable=True),
    sa.Column('is_tradeable', sa.Boolean(), nullable=False),
    sa.Column('is_repo_eligible', sa.Boolean(), nullable=False),
    sa.Column('haircut_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.CheckConstraint('coupon_rate >= 0', name='ck_security_coupon_positive'),
    sa.CheckConstraint('maturity_date > issue_date', name='ck_security_maturity_after_issue'),
    sa.ForeignKeyConstraint(['issuer_id'], ['entity_master.entity_id'], ),
    sa.PrimaryKeyConstraint('security_id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index('ix_security_isin', 'security_master', ['isin'], unique=False)
    op.create_index('ix_security_maturity', 'security_master', ['maturity_date'], unique=False)
    op.create_index('ix_security_type', 'security_master', ['security_type'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('full_name_th', sa.String(length=100), nullable=True),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.Column('api_key_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_user_email', 'users', ['email'], unique=False)
    op.create_index('ix_user_role', 'users', ['role'], unique=False)
    op.create_index('ix_user_username', 'users', ['username'], unique=False)
    op.create_table('bond_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_date', sa.Date(), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('portfolio_id', sa.String(length=40), nullable=False),
    sa.Column('security_id', sa.String(length=40), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('accrued_interest', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('tfrs9_classification', sa.String(length=20), nullable=False),
    sa.Column('ecl_stage', sa.Integer(), nullable=False),
    sa.Column('ecl_provision', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pledged_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_master.portfolio_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security_master.security_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_date', 'portfolio_id', 'security_id', name='uq_bond_position')
    )
    op.create_index('ix_bond_pos_date', 'bond_positions', ['position_date'], unique=False)
    op.create_index('ix_bond_pos_portfolio', 'bond_positions', ['portfolio_id'], unique=False)
    op.create_index('ix_bond_pos_security', 'bond_positions', ['security_id'], unique=False)
    op.create_table('bond_trades',
    sa.Column('trade_id', sa.String(length=40), nullable=False),
    sa.Column('trade_ref', sa.String(length=50), nullable=False),
    sa.Column('external_ref', sa.String(length=50), nullable=True),
    sa.Column('thaibma_ref', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('portfolio_id', sa.String(length=40), nullable=False),
    sa.Column('security_id', sa.String(length=40), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('trade_side', sa.String(length=10), nullable=False),
    sa.Column('trade_type', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('face_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('clean_price', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('dirty_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('yield_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('settlement_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('broker_fee', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('withholding_tax', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_thaibma_reported', sa.Boolean(), nullable=False),
    sa.Column('thaibma_report_time', sa.DateTime(), nullable=True),
    sa.Column('trader_id', sa.String(length=40), nullable=True),
    sa.Column('approver_id', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('settlement_status', sa.String(length=30), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('settlement_ref', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('face_value > 0', name='ck_bond_face_value_positive'),
    sa.CheckConstraint('settlement_date >= trade_date', name='ck_bond_settlement_after_trade'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty_master.counterparty_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_master.portfolio_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security_master.security_id'], ),
    sa.PrimaryKeyConstraint('trade_id'),
    sa.UniqueConstraint('trade_ref')
    )
    op.create_index('ix_bond_counterparty', 'bond_trades', ['counterparty_id'], unique=False)
    op.create_index('ix_bond_security', 'bond_trades', ['security_id'], unique=False)
    op.create_index('ix_bond_settlement_date', 'bond_trades', ['settlement_date'], unique=False)
    op.create_index('ix_bond_status', 'bond_trades', ['status'], unique=False)
    op.create_index('ix_bond_trade_date', 'bond_trades', ['trade_date'], unique=False)
    op.create_table('interbank_deals',
    sa.Column('deal_id', sa.String(length=40), nullable=False),
    sa.Column('deal_ref', sa.String(length=50), nullable=False),
    sa.Column('external_ref', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('portfolio_id', sa.String(length=40), nullable=False),
    sa.Column('deal_type', sa.String(length=20), nullable=False),
    sa.Column('deal_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('rate_type', sa.String(length=10), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('spread', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('reference_rate', sa.String(length=20), nullable=True),
    sa.Column('day_count_convention', sa.String(length=20), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('maturity_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trader_id', sa.String(length=40), nullable=True),
    sa.Column('approver_id', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('start_settlement_status', sa.String(length=30), nullable=False),
    sa.Column('start_settled_at', sa.DateTime(), nullable=True),
    sa.Column('start_bahtnet_ref', sa.String(length=50), nullable=True),
    sa.Column('maturity_settlement_status', sa.String(length=30), nullable=False),
    sa.Column('maturity_settled_at', sa.DateTime(), nullable=True),
    sa.Column('maturity_bahtnet_ref', sa.String(length=50), nullable=True),
    sa.Column('is_early_terminated', sa.Boolean(), nullable=False),
    sa.Column('early_termination_date', sa.Date(), nullable=True),
    sa.Column('early_termination_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('maturity_date > start_date', name='ck_ib_maturity_after_start'),
    sa.CheckConstraint('principal_amount > 0', name='ck_ib_principal_positive'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty_master.counterparty_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_master.portfolio_id'], ),
    sa.PrimaryKeyConstraint('deal_id'),
    sa.UniqueConstraint('deal_ref')
    )
    op.create_index('ix_ib_counterparty', 'interbank_deals', ['counterparty_id'], unique=False)
    op.create_index('ix_ib_deal_date', 'interbank_deals', ['deal_date'], unique=False)
    op.create_index('ix_ib_deal_type', 'interbank_deals', ['deal_type'], unique=False)
    op.create_index('ix_ib_maturity_date', 'interbank_deals', ['maturity_date'], unique=False)
    op.create_index('ix_ib_status', 'interbank_deals', ['status'], unique=False)
    op.create_table('limit_definitions',
    sa.Column('limit_id', sa.String(length=40), nullable=False),
    sa.Column('limit_type', sa.String(length=30), nullable=False),
    sa.Column('limit_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=True),
    sa.Column('security_id', sa.String(length=40), nullable=True),
    sa.Column('portfolio_id', sa.String(length=40), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('warning_threshold_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_tenor_days', sa.Integer(), nullable=True),
    sa.Column('max_tenor_days', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.CheckConstraint('limit_amount > 0', name='ck_limit_amount_positive'),
    sa.CheckConstraint('warning_threshold_pct > 0 AND warning_threshold_pct <= 100', name='ck_limit_warning_valid'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty_master.counterparty_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_master.portfolio_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security_master.security_id'], ),
    sa.PrimaryKeyConstraint('limit_id')
    )
    op.create_index('ix_limit_counterparty', 'limit_definitions', ['counterparty_id'], unique=False)
    op.create_index('ix_limit_entity', 'limit_definitions', ['entity_id'], unique=False)
    op.create_index('ix_limit_type', 'limit_definitions', ['limit_type'], unique=False)
    op.create_table('net_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_date', sa.Date(), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('security_id', sa.String(length=40), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('long_position', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('short_position', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('net_position', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('realized_pnl_today', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security_master.security_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_date', 'entity_id', 'security_id', name='uq_net_position')
    )
    op.create_index('ix_net_pos_date', 'net_positions', ['position_date'], unique=False)
    op.create_table('repo_trades',
    sa.Column('trade_id', sa.String(length=40), nullable=False),
    sa.Column('trade_ref', sa.String(length=50), nullable=False),
    sa.Column('external_ref', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('portfolio_id', sa.String(length=40), nullable=False),
    sa.Column('trade_type', sa.String(length=20), nullable=False),
    sa.Column('repo_type', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('near_leg_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('far_leg_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('repo_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('rate_type', sa.String(length=10), nullable=False),
    sa.Column('day_count_convention', sa.String(length=20), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('collateral_security_id', sa.String(length=40), nullable=True),
    sa.Column('collateral_isin', sa.String(length=12), nullable=True),
    sa.Column('collateral_face_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('collateral_market_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('haircut_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('initial_margin', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_margin', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('margin_call_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trader_id', sa.String(length=40), nullable=True),
    sa.Column('approver_id', sa.String(length=40), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('near_leg_cash_status', sa.String(length=30), nullable=False),
    sa.Column('near_leg_collateral_status', sa.String(length=30), nullable=False),
    sa.Column('near_leg_settled_at', sa.DateTime(), nullable=True),
    sa.Column('far_leg_cash_status', sa.String(length=30), nullable=False),
    sa.Column('far_leg_collateral_status', sa.String(length=30), nullable=False),
    sa.Column('far_leg_settled_at', sa.DateTime(), nullable=True),
    sa.Column('is_early_terminated', sa.Boolean(), nullable=False),
    sa.Column('early_termination_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='ck_repo_end_after_start'),
    sa.CheckConstraint('near_leg_amount > 0', name='ck_repo_amount_positive'),
    sa.ForeignKeyConstraint(['collateral_security_id'], ['security_master.security_id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty_master.counterparty_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_master.portfolio_id'], ),
    sa.PrimaryKeyConstraint('trade_id'),
    sa.UniqueConstraint('trade_ref')
    )
    op.create_index('ix_repo_end_date', 'repo_trades', ['end_date'], unique=False)
    op.create_index('ix_repo_start_date', 'repo_trades', ['start_date'], unique=False)
    op.create_index('ix_repo_status', 'repo_trades', ['status'], unique=False)
    op.create_index('ix_repo_trade_date', 'repo_trades', ['trade_date'], unique=False)
    op.create_index('ix_repo_type', 'repo_trades', ['trade_type'], unique=False)
    op.create_table('user_sessions',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('terminated_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_session_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_session_user', 'user_sessions', ['user_id'], unique=False)
    op.create_table('collateral_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_date', sa.Date(), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('repo_trade_id', sa.String(length=40), nullable=False),
    sa.Column('security_id', sa.String(length=40), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('is_pledged', sa.Boolean(), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('haircut_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('collateral_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('required_margin', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('excess_margin', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('margin_call_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty_master.counterparty_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_master.entity_id'], ),
    sa.ForeignKeyConstraint(['repo_trade_id'], ['repo_trades.trade_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security_master.security_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collateral_pos_date', 'collateral_positions', ['position_date'], unique=False)
    op.create_index('ix_collateral_repo', 'collateral_positions', ['repo_trade_id'], unique=False)
    op.create_index('ix_collateral_security', 'collateral_positions', ['security_id'], unique=False)
    op.create_table('limit_breaches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('breach_date', sa.DateTime(), nullable=False),
    sa.Column('limit_id', sa.String(length=40), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('utilized_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('breach_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('breach_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('trade_ref', sa.String(length=50), nullable=True),
    sa.Column('trade_type', sa.String(length=30), nullable=True),
    sa.Column('trader_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=40), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['limit_id'], ['limit_definitions.limit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_breach_date', 'limit_breaches', ['breach_date'], unique=False)
    op.create_index('ix_breach_limit', 'limit_breaches', ['limit_id'], unique=False)
    op.create_index('ix_breach_status', 'limit_breaches', ['status'], unique=False)
    op.create_table('limit_utilizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilization_date', sa.Date(), nullable=False),
    sa.Column('limit_id', sa.String(length=40), nullable=False),
    sa.Column('utilized_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('available_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('utilization_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_warning', sa.Boolean(), nullable=False),
    sa.Column('is_breached', sa.Boolean(), nullable=False),
    sa.Column('last_trade_ref', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['limit_id'], ['limit_definitions.limit_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilization_date', 'limit_id', name='uq_limit_utilization')
    )
    op.create_index('ix_util_breach', 'limit_utilizations', ['is_breached'], unique=False)
    op.create_index('ix_util_date', 'limit_utilizations', ['utilization_date'], unique=False)
    op.create_index('ix_util_limit', 'limit_utilizations', ['limit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_util_limit', table_name='limit_utilizations')
    op.drop_index('ix_util_date', table_name='limit_utilizations')
    op.drop_index('ix_util_breach', table_name='limit_utilizations')
    op.drop_table('limit_utilizations')
    op.drop_index('ix_breach_status', table_name='limit_breaches')
    op.drop_index('ix_breach_limit', table_name='limit_breaches')
    op.drop_index('ix_breach_date', table_name='limit_breaches')
    op.drop_table('limit_breaches')
    op.drop_index('ix_collateral_security', table_name='collateral_positions')
    op.drop_index('ix_collateral_repo', table_name='collateral_positions')
    op.drop_index('ix_collateral_pos_date', table_name='collateral_positions')
    op.drop_table('collateral_positions')
    op.drop_index('ix_session_user', table_name='user_sessions')
    op.drop_index('ix_session_expires', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_repo_type', table_name='repo_trades')
    op.drop_index('ix_repo_trade_date', table_name='repo_trades')
    op.drop_index('ix_repo_status', table_name='repo_trades')
    op.drop_index('ix_repo_start_date', table_name='repo_trades')
    op.drop_index('ix_repo_end_date', table_name='repo_trades')
    op.drop_table('repo_trades')
    op.drop_index('ix_net_pos_date', table_name='net_positions')
    op.drop_table('net_positions')
    op.drop_index('ix_limit_type', table_name='limit_definitions')
    op.drop_index('ix_limit_entity', table_name='limit_definitions')
    op.drop_index('ix_limit_counterparty', table_name='limit_definitions')
    op.drop_table('limit_definitions')
    op.drop_index('ix_ib_status', table_name='interbank_deals')
    op.drop_index('ix_ib_maturity_date', table_name='interbank_deals')
    op.drop_index('ix_ib_deal_type', table_name='interbank_deals')
    op.drop_index('ix_ib_deal_date', table_name='interbank_deals')
    op.drop_index('ix_ib_counterparty', table_name='interbank_deals')
    op.drop_table('interbank_deals')
    op.drop_index('ix_bond_trade_date', table_name='bond_trades')
    op.drop_index('ix_bond_status', table_name='bond_trades')
    op.drop_index('ix_bond_settlement_date', table_name='bond_trades')
    op.drop_index('ix_bond_security', table_name='bond_trades')
    op.drop_index('ix_bond_counterparty', table_name='bond_trades')
    op.drop_table('bond_trades')
    op.drop_index('ix_bond_pos_security', table_name='bond_positions')
    op.drop_index('ix_bond_pos_portfolio', table_name='bond_positions')
    op.drop_index('ix_bond_pos_date', table_name='bond_positions')
    op.drop_table('bond_positions')
    op.drop_index('ix_user_username', table_name='users')
    op.drop_index('ix_user_role', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_security_type', table_name='security_master')
    op.drop_index('ix_security_maturity', table_name='security_master')
    op.drop_index('ix_security_isin', table_name='security_master')
    op.drop_table('security_master')
    op.drop_table('portfolio_master')
    op.drop_index('ix_counterparty_type', table_name='counterparty_master')
    op.drop_index('ix_counterparty_bot_code', table_name='counterparty_master')
    op.drop_table('counterparty_master')
    op.drop_index('ix_cash_pos_entity', table_name='cash_positions')
    op.drop_index('ix_cash_pos_date', table_name='cash_positions')
    op.drop_table('cash_positions')
    op.drop_index('ix_haircut_security_type', table_name='haircut_matrix')
    op.drop_table('haircut_matrix')
    op.drop_index('ix_entity_swift', table_name='entity_master')
    op.drop_index('ix_entity_bot_code', table_name='entity_master')
    op.drop_table('entity_master')
    op.drop_index('ix_audit_user', table_name='audit_logs')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
